### ISSUE TITLE
分隔符打句模式下符号顶句上屏问题

### ISSUE THREAD

**Issue by arockshan** [Ace-Who/rime-xuma#1]
「徐码·QS」方案，输入分隔符「`」进入打句模式后，无论分隔符前面的编码多长，若分隔符后面的编码对应的汉字超过四个，用符号顶第一候选上屏时，只有符号上屏。
前面是编码中只有一个分隔符的情况，若有多个分隔符，则从最后一个分隔符计。即最后一个分隔符后的编码对应的汉字不能超过四个，否则符号顶字上屏会只有符号上屏。
在无分隔符的打句模式下，多长的句子都可以通过符号顶句上屏。

**Comment by Ace-Who** [comment]
抱歉，本顶目一直没人提 issue，现在才注意到这个。
1. 未能重现这个问题，请提供实例。
2. 本方案只有输入分隔符「`」才会进入连打模式，「无分隔符的打句模式」是如何做的，对方案做了什么修改？

**Comment by arockshan** [comment]
确实，用语言描述一个操作太不经济，我本应该提供例子说明的，我的例子是以「徐码·QS」打「夫何环逸之令姿独旷世以秀群表倾城之艳色期有德于传闻」（夫何环逸之令姿，独旷世以秀群。表倾城之艳色，期有德于传闻。）这句话。
我首先解释下我所谓的「无分隔符的打句模式」。如，打头两字「夫何」（jfteo），便可看到第一候选后有太极☯图标，在我对Rime和「徐码」马马虎虎的了解中，这就是进入「打句模式」了。下面是打整个长句复现问题。
1. 夫何环逸之令姿独旷世以秀群（jfteoegbqowzzzuwdxqcvlvkw`hscwuuranbpox。）：在「旷」（kw）后插入分隔符，「旷」后四个字「世以秀群」输完，以句号「，」，「。」或数字键「1」顶字上屏。 
2. 在前句的基础上，试输入「夫何环逸之令姿独旷世以秀群表（jfteoegbqowzzzuwdxqcvlvkw`hscwuuranbpoxer）」：照旧在「旷」（kw）后插入分隔符，「旷」后五个字「世以秀群表」输完，尝试以「，」，「。」，数字键「1」上屏句子，问题便会出现。在不同的软件中，问题表现有差异，大体是：若悬浮框消失，那么便只有用来顶句的符号的半角形式上屏——我的「word文档」里是这样的；若悬浮框不消失，便会每按一次顶句符号，悬浮框闪烁一次，同时顶句符号的半角形式上屏一次，然而再换「空格」键上屏，会发现句子上屏了，而之前上屏的半角符号也没有了——在chrome浏览器中写这个issue回复时是这样。又，在我的小米手机中，「同文输入法」这个问题表现为，没有字符上屏同时悬浮框消失。  
3. 我的电脑是win10的，「徐码·QS」是2020-05-27的版本，「xuma·dict」是2020.07.14的版本。我对「徐码·QS」所做的改动仅限些参数——可reset的和true-false可选的；其中与打句相关的我想是speller和translator部分的代码，我关闭了自动造词，改动参数也没有起作用。下面是「徐码·QS」改动后的代码：
`# Rime schema settings`
`# encoding: utf-8`
schema:
  schema_id: xuma_qshare
  name: 徐码·QS
  version: "2020-05-27"
  author:
    - 發明人 徐国银先生
    - rime schema by Q
  description: |
    徐码简繁通打
    chinput.com/xuma

    三重注解、双重反查、屏蔽词组、全码后置、简入繁出...
    https://ace-who.github.io/rime-xuma/
  dependencies:
    - xuma_spelling_pseudo
    - luna_pinyin
    - stroke

__patch:
  - xuma_qshare.custom:/patch?
  - symbols:/patch?

switches:
  - options: [ gb2312, gbk, big5, utf8 ]
    states: [ gb2312, GBK, BIG5, UTF-8 ]
    reset: 3
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
    #reset: 0
  - name: simplification
    states: [ 漢字, 汉字 ]
    reset: 0
  - name: traditionalization
    reset: 0
    states: [ 简体保持, 簡入繁出 ]
  - name: ascii_punct
    states: [ 。，, ．， ]
    #reset: 1
  - name: xuma_spelling  # 三重注解
    #reset: 1
    states: [ 拆, 扌⺁丅丶 ]
  - name: xmsp_hide_pinyin  # 是否显示三重注解中的拼音
    states: [ 音, 哑 ]
    #reset: 1
  - name: xuma_postpone_fullcode  # 仅作用于单字。
    reset: 0
    states: [ ＝原始排序, ↓全码后置 ]
  - name: single_char_only
    states: [ 词组派, 单字派 ]
    #reset: 0
  - name: lazy_clock
    states: [ 懒钟下班, ㍡开工 ]

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - affix_segmentor@luna_pinyin
    - affix_segmentor@luna_pinyin_lookup
    - affix_segmentor@stroke_lookup
    - affix_segmentor@reverse_lookup
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - history_translator@history
    - table_translator@fixed
    - table_translator
    - script_translator@luna_pinyin
    - script_translator@luna_pinyin_lookup
    - table_translator@stroke_lookup
    - lua_translator@os_env
    - lua_translator@helper
  filters:
    - lua_filter@single_char_only
    - charset_filter@gb2312
    - charset_filter@gbk
    - charset_filter@big5
    - charset_filter@utf8
    - simplifier@simplify
    - simplifier@traditionalize
    - reverse_lookup_filter@luna_pinyin_reverse_lookup
    - reverse_lookup_filter@stroke_reverse_lookup
    - lua_filter@xuma_spelling@xmsp
    - lua_filter@xuma_spelling@xmsp_for_rvlk
    - lua_filter@xuma_postpone_fullcode
    - lua_filter@lazy_clock
    - uniquifier
    # - lua_filter@debug_filter

single_char_only:
  __include: gb2312

`# 防止对 punct 进行过滤`
gb2312:
  tags: [ abc, reverse_lookup, luna_pinyin_lookup, stroke_lookup ]
gbk:
  __include: gb2312
big5:
  __include: gb2312

simplify:
  __include: gb2312
  option_name: simplification
  tips: all

traditionalize:
  __include: gb2312
  opencc_config: s2t.json
  option_name: traditionalization
  tips: all
  comment_format:
    - xform/^/（/
    - xform/$/）/

lua_reverse_db:
  spelling: xuma_spelling_pseudo
  code: xuma

xmsp:
  tags: [ abc, punct ]

xmsp_for_rvlk:
  tags:
    __include: reverse_lookup/extra_tags

xuma_postpone_fullcode:
  tags: [ abc ]

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " `'"
  max_code_length: 4
  #auto_select: true
  algebra:
    - xform/^\*//  # 特码以星号开头，以便在全码后置脚本中区分，以防识别为全码

fixed:
  __include: translator
  enable_user_dict: false
  enable_sentence: false
  initial_quality: 1000

translator:
  dictionary: xuma
  prism: xuma_qshare
  enable_sentence: true
  enable_user_dict: false
  enable_encoder: false
  encode_commit_history: false  # 对连续上屏的词自动成词
  max_phrase_length: 10  # 自动成词的最大词长
  preedit_format:
    - 'xform/^([a-z]*)$/$1\t（\U$1\E）/'
    - "xlit|ABCDEFGHIJKLMNOPQRSTUVWXYZ|糸阝女尸王扌石艹木土日虫山目口⺮魚禾月亻忄金宀火言氵|"

history:
  input: dl
  size: 5
  initial_quality: 2000

#用于混输
luna_pinyin:
  tag: luna_pinyin
  dictionary: luna_pinyin
  initial_quality: 0.2

#拼音混输。不使用 luna_pinyin_lookup，是因为那样做会导致所有常规编码段和常规候
#选被同时打上 abc 和 luna_pinyin_lookup 标签，从而同时被 xmsp 和 xmsp_for_rvlk
#接收，被添加两次注释。
#abc_segmentor:
   #extra_tags: [ luna_pinyin ]

reverse_lookup:
  tag: reverse_lookup
  prefix: "`"    # 反查引导符「`」
   #suffix:   # 反查关闭符，暂不定义
  tips: 【反查：拼音+笔画】
  closing_tips: 【反查关闭】
   #preedit_format:
     #- xform/([nljqxy])v/$1ü/
  extra_tags:
    - luna_pinyin_lookup
    - stroke_lookup

luna_pinyin_lookup:
  tag: luna_pinyin_lookup
  dictionary: luna_pinyin
  prefix: '`P'
  tips: 【朙月拼音反查】
  closing_tips: 【反查关闭】
  initial_quality: 0.2

stroke_lookup:
  tag: stroke_lookup
  dictionary: stroke
  prefix: '`B'
  tips: 【五笔画反查】
  closing_tips: 【反查关闭】
  initial_quality: 0.5
  preedit_format:
    - 'xform/^([hspnz]+)$/$1\t（\U$1\E）/'
    - xlit/HSPNZ/一丨丿丶乙/

luna_pinyin_reverse_lookup:
  tags: [ luna_pinyin, luna_pinyin_lookup ]
  dictionary: xuma
   #overwrite_comment: true  # 覆蓋其他提示

stroke_reverse_lookup:
  __include: luna_pinyin_reverse_lookup
  tags: [ stroke_lookup ]

punctuator:
  import_preset: default
  #import_preset: symbols

#本节点仅用于被 __patch 指令引用
key_bindings:
  __append:
    - { when: always, accept: "Control+Shift+F", toggle: traditionalization }
    - { when: composing, accept: "Control+c", toggle: xuma_spelling }
    - { when: composing, accept: "Control+y", toggle: xmsp_hide_pinyin }
    - { when: composing, accept: "Control+s", toggle: single_char_only }
    - { when: composing, accept: "Control+t", toggle: lazy_clock }
     #default 中的预设包括逗号和句号翻页，在此取消
    - { when: has_menu, accept: comma, send: comma }
    - { when: has_menu, accept: period, send: period }
    - { when: has_menu, accept: semicolon, send: 2 }  # 分号次选
    - { when: has_menu, accept: apostrophe, send: 3 }  # 引号三选

key_binder:
  import_preset: default
  bindings:
    __patch:
      - key_bindings
       #可仿照 key_bindings 根节点在 *.custom.yaml 文件中添加按键绑定。
      - xuma_qshare.custom:/keybindings?

recognizer:
   #import_preset: default
  patterns:
    uppercase: "[^`;]*[A-Z][-_+.'0-9A-Za-z]*$"
    reverse_lookup:     "`([a-z]+'?)*$"
    luna_pinyin_lookup: "`P([a-z]+'?)*$"
    stroke_lookup:      "`B([a-z]+'?)*$"
    os_env: '^env/\w+'
    helper: '^help/$'
`

**Comment by Ace-Who** [comment]
问题出在最后几行，可改为：

```yaml
    reverse_lookup:     "^`([a-z]+'?)*$"
    luna_pinyin_lookup: "^`P([a-z]+'?)*$"
    stroke_lookup:      "^`B([a-z]+'?)*$"
```

另外发现，当 `translator/enable_user_dict` 为 `true` 时，二次打句会无法自动重现首次的断句，原因不明，可以适当插入分隔符来解决。你已经改成了 `false`，这样似乎能避免这个问题。为允许自造词，将来还是会维持 `true` 的设定，快速打句的体验会受影响，但是整句不是四码限长类方案的最佳实践，所以优先照顾为字词模式服务的功能。

**Comment by arockshan** [comment]
问题完美解决！谢谢Ace！
