### ISSUE TITLE
MacOS 11.6 自符集过滤无效

### ISSUE THREAD

**Issue by forFudan** [Ace-Who/rime-xuma#9]
操作系统: MacOS 11.6
Rime: Squirrel-0.15.2
问题:
在MacOS上安装Squirrel后,拷贝本输入法schema文件夹下所有文件到Rime文件夹下.未进行任何其他设置.
选择任何字符集都无法成功过滤非常用字符,比如:选定"gb2312"后,输入"wyzx"依旧可以出现"𰻝"字.
重新安装Squirrel两次,问题未能解決.
如图:
![Screen Shot 2021-12-06 at 14 23 26](https://user-images.githubusercontent.com/12560439/144859893-0ac0655c-c79e-4819-87d7-70183f64ea32.png)

![Screen Shot 2021-12-06 at 14 23 52](https://user-images.githubusercontent.com/12560439/144858782-3be70939-7544-4d9a-b9a7-bc74c865b93f.png)

**Comment by Ace-Who** [comment]
大概是该版 rime 程序的问题。

**Comment by forFudan** [comment]
> 大概是该版 rime 程序的问题。
根据这个讨论，的确是的。[https://github.com/rime/librime/issues/335#issuecomment-569871506](url)
原因是librime-charcode被剥离出来做为插件，导致主引擎中不内置字符集过滤了。

**Comment by Ace-Who** [comment]
可以尝试替换为含插件的版本：https://github.com/rime/librime/releases

**Comment by Ace-Who** [comment]
这个理由挺奇怪的，因为 librime-lua 也是插件，它应该还在 0.15.2 中吧。

**Comment by forFudan** [comment]
> 这个理由挺奇怪的，因为 librime-lua 也是插件，它应该还在 0.15.2 中吧。

不知道了. 但是我不想自己编译老的版本.所以写了个[暴力字符集filter](https://github.com/forFudan/rime/blob/main/lua/character_filter/filter_gbk.lua)的脚本在Squirrel上用.希望这个功能以后在Squirrel中可以被恢复.
